services:
  mysql:
    image: mysql:8.4
    container_name: pamahe_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:?DB_NAME no definido}
      MYSQL_USER: ${DB_USER:?DB_USER no definido}
      MYSQL_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD no definido}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?DB_ROOT_PASSWORD no definido}
    ports:
      - "3307:3306"
    volumes:
      - pamahe_mysql_data:/var/lib/mysql

volumes:
  pamahe_mysql_data: